### ISSUE TITLE
Failure to start run-vmblock\x2dfuse.mount

### ISSUE THREAD

**Issue by fsch2** [vmware/open-vm-tools#170]
Hi there,

I cannot start the run-vmblock\x2dfuse.mount. The output:
```
~ % sudo systemctl start run-vmblock\\x2dfuse.mount
Job for run-vmblock\x2dfuse.mount failed.
See "systemctl status "run-vmblock\\x2dfuse.mount"" and "journalctl -xe" for details.
~ % sudo systemctl status run-vmblock\\x2dfuse.mount -l
```
If I check what is wrong:
```
● run-vmblock\x2dfuse.mount - VMware vmblock fuse mount
   Loaded: loaded (/lib/systemd/system/run-vmblock\x2dfuse.mount; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-06-13 09:23:47 CEST; 1min 45s ago
    Where: /run/vmblock-fuse
     What: vmware-vmblock-fuse
     Docs: https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/vmblock-fuse/design.txt
  Process: 6534 ExecMount=/bin/mount vmware-vmblock-fuse /run/vmblock-fuse -t fuse -o subtype=vmware-vmblock,default_permissions,allow_other (code=exited, status=255)

Jun 13 09:23:47 sikanda systemd[1]: Mounting VMware vmblock fuse mount...
Jun 13 09:23:47 sikanda systemd[1]: run-vmblock\x2dfuse.mount: Mount process exited, code=exited status=255
Jun 13 09:23:47 sikanda systemd[1]: Failed to mount VMware vmblock fuse mount.
Jun 13 09:23:47 sikanda systemd[1]: run-vmblock\x2dfuse.mount: Unit entered failed state.
```
I just thought, this is not the expected behavior (mount exit code 255), so opened this issue.

This is not such a big issue for me, because copy/paste, multiple monitors and correct resolution detection work for me. I need to start the `vmtoolsd -n vmusr`-process manually with `vmware-user-suid-wrapper`, but then it works. This prints the message `vmware-user: could not open /proc/fs/vmblock/dev`, but I learned in the meantime, that this can be safely ignored.

My system:
- Debian 9.0 with XFCE 4.12
- Kernel 4.9.0
- open-vm-tools and open-vm-tools-desktop installed, version 10.1.5

Cheers!

**Comment by oliverkurth** [comment]
I am not able to reproduce this in a Debian/sid VM running open-vm-tools 2:10.1.5-5055683-4 (current version in both sid and stretch). Which exact package version do you have installed (`dpkg -l open-vm-tools-desktop`)? Also, can you please attach your version of the file `/lib/systemd/system/run-vmblock\x2dfuse.mount` just in case it has been modified.

**Comment by urherenow** [comment]
22.04.1 LTS Ubuntu here and I get this error along with
Failed to start LSB: VMware Tools service

**Comment by johnwvmw** [comment]
@urherenow 
You have posted to a 5 year old issue that we should have closed since there was no response from the original poster.  A lot has changed since 2017.

Please open a new issue and provide the follow information so that we may try to reproduce the problem in house. 

Hypervisor - ESX, Workstation or Fusion along with product version
Architecture - i386, x86_64/amd64 or ARM
Version of open-vm-tools packages installed on you Ubuntu 22.04 LTS 
   ( collect output of "apt list --installed | grep open-vm-tools" )
   
Please elaborate on contents of  "this error".

As the original issue was run was with the vmblock/fuse  mount service, please collect the output of the command 

   **systemctl status run-vmblock\\x2dfuse.mount**
   
   Note: the two backslashes are necessary here.
   
Thanks

**Comment by Novice-me** [comment]
> 22.04.1 LTS Ubuntu here and I get this error along with Failed to start LSB: VMware Tools service

This problem may be related to the ```lib fuse``` of Ubuntu 22.04. You can try
```sudo apt install libfuse2```

**Comment by shiyandong** [comment]
> > 22.04.1 LTS Ubuntu here and I get this error along with Failed to start LSB: VMware Tools service
> 
> This problem may be related to the `lib fuse` of Ubuntu 22.04. You can try `sudo apt install libfuse2`

it works, thanks you!

**Comment by urherenow** [comment]
Fixed me up too. Been home from deployment for just a couple of weeks, so I’ve been too busy to reply. Thanks  @Novice-me!

**Comment by apg8431** [comment]
Hi, I tried installing the libfuse2 package but keep getting the same error when launching the x2dfuse.mount via systemctl: using Lubuntu 22.04

**Comment by dinamic** [comment]
I seem to already have `libfuse2` installed yet the issue persists.

This happens on a Macbook Pro with Apple M1 with Kali Linux arm64 installed.

```
┌──(nikola㉿fb1)-[~]
└─$ sudo restart-vm-tools    
Job failed. See "journalctl -xe" for details.
                                                                                                                           
┌──(nikola㉿fb1)-[~]
└─$ journalctl -xe       
Jun 06 14:01:38 fb1 systemd[1]: run-vmblock\x2dfuse.mount: Mount process exited, code=exited, status=32/n/a
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An n/a= process belonging to unit run-vmblock\x2dfuse.mount has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 32.
Jun 06 14:01:38 fb1 systemd[1]: Failed unmounting run-vmblock\x2dfuse.mount - VMware vmblock fuse mount.
░░ Subject: A stop job for unit run-vmblock\x2dfuse.mount has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A stop job for unit run-vmblock\x2dfuse.mount has finished.
░░ 
░░ The job identifier is 2880 and the job result is failed.
Jun 06 14:01:38 fb1 systemd[1]: open-vm-tools.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit open-vm-tools.service has successfully entered the 'dead' state.
Jun 06 14:01:40 fb1 systemd[1]: Starting open-vm-tools.service - Service for virtual machines hosted on VMware...
░░ Subject: A start job for unit open-vm-tools.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit open-vm-tools.service has begun execution.
░░ 
░░ The job identifier is 2885.
Jun 06 14:01:40 fb1 systemd[1]: Started open-vm-tools.service - Service for virtual machines hosted on VMware.
░░ Subject: A start job for unit open-vm-tools.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit open-vm-tools.service has finished successfully.
░░ 
░░ The job identifier is 2885.
Jun 06 14:01:40 fb1 systemd[1]: Reloading.
Jun 06 14:01:40 fb1 sudo[7583]: pam_unix(sudo:session): session closed for user root
                                                                                                                           
┌──(nikola㉿fb1)-[~]
└─$ sudo apt install libfuse2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libfuse2 is already the newest version (2.9.9-6+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
                                                                                                                           
┌──(nikola㉿fb1)-[~]
└─$ uname -a 
Linux fb1 6.1.0-kali9-arm64 #1 SMP Debian 6.1.27-1kali1 (2023-05-12) aarch64 GNU/Linux
                                                                                                                           
┌──(nikola㉿fb1)-[~]
└─$ 


```
