### ISSUE TITLE
Fedora 30 guest will not start after installation and hangs with black screen and high VMX CPU usage on VMware Workstation 15.0.4 Pro for Windows

### ISSUE THREAD

**Issue by hermidalc** [vmware/open-vm-tools#339]
Fedora 30 guest installs without issue, but after hitting the Reboot button at end of graphical installer everything reboots, successfully gets through the Fedora bootloader and then screen stays black and boot hangs.  System is unresponsive and doesn't respond to shutdown guest.  VMX process CPU usage on one core is maxed.

**Comment by thomashvmw** [comment]
Hi!
I just downloaded Fedora 30 installed, updated and rebooted without problem. My fedora 29 VM is running Plymouth 0.9.4. 
Having said that, The vmware display drivers are not part of open-vm-tools so bugs should really be filed in the fdo bugzilla, but if you think the problem is caused by a fedora plymouth update, you should really contact fedora about this!

Thanks,
Thomas

**Comment by hermidalc** [comment]
> I just downloaded Fedora 30 installed, updated and rebooted without problem. My fedora 29 VM is running Plymouth 0.9.4-2, and I see no issues.

> Having said that, The vmware display drivers are not part of open-vm-tools so bugs should really be filed in the fdo bugzilla, but if you think the problem is caused by a fedora plymouth update, you should really contact fedora about this!

@thomashvmw as I said in my OP, it's not Fedora, otherwise I wouldn't be wasting your time :-).  If it were Fedora I would see others online having this problem.  It's something with vmware.  Also, I would hazard a guess that it's not an issue with the vmware display drivers, something is getting stuck during the guest boot right when the screen is supposed to temporarily go black after the bootloader finishes and before GNOME show up.  It could be something totally unrelated to graphics. 

May I ask in your Fedora 30 install what were your vmx settings?  Maybe one of my settings is causing the problem.

**Comment by hermidalc** [comment]
Hi @thomashvmw - I'm going to try another Fedora 30 fresh install, may I ask did you do all default vmx settings in your test?

**Comment by hermidalc** [comment]
@thomashvmw I found the problem, it is something with VMware

**Comment by thomashvmw** [comment]
@hermidalc 
While I couldn't reproduce it myself, a collegue could, so we'll look into the issue as soon as possible. It might be a VMware vmwgfx kernel bug considering the hang with high cpu.

**Comment by hermidalc** [comment]
> @hermidalc
> While I couldn't reproduce it myself, a collegue could, so we'll look into the issue as soon as possible. It might be a VMware vmwgfx kernel bug considering the hang with high cpu.

One of the posts on https://communities.vmware.com/thread/606594 (the one with the screenshots) said they managed to get into the system as it was hanging and saw that **plymouthd** daemon was using all of one of the virtual procs as it was trying to start the graphical boot.  Hope this helps.

**Comment by thomashvmw** [comment]
There is a plymouthd and a vmwgfx kernel driver component to this issue. The vmwgfx fixes are ready inhouse and will be submitted upstream soon. I've filed a plymouthd bug at 

https://bugzilla.redhat.com/show_bug.cgi?id=1707307

**Comment by hermidalc** [comment]
Thanks @thomashvmw for troubleshooting this so quickly, that's why I post vmware issues here you guys know what you are doing!

**Comment by surajrao97** [comment]
> There is a plymouthd and a vmwgfx kernel driver component to this issue.

Any update on this issue? Thanks.

**Comment by hermidalc** [comment]
> > There is a plymouthd and a vmwgfx kernel driver component to this issue.
> 
> Any update on this issue? Thanks.

I believe @thomashvmw fixed the vmwgfx issue and it's slated to be included in a future version of vmware.  For plymouthd check the redhat bugzilla as this is redhat's problem

**Comment by hermidalc** [comment]
To users coming here wondering if the fix made it into VMware Workstation 15.1.0 it didn't yet.

**Comment by thomashvmw** [comment]
The fixes will not be part of anything VMware ships. They will come with your distro's regular updates once accepted upstream. Hopefully the patches are in Linus' kernel tree by next Monday, and after that it's up to the distro to pick them up.

**Comment by hermidalc** [comment]
> The fixes will not be part of anything VMware ships. They will come with your distro's regular updates once accepted upstream. Hopefully the patches are in Linus' kernel tree by next Monday, and after that it's up to the distro to pick them up.

Thanks for the clarification and sorry for the confusion (thought vmwgfx was part of what VMware ships)

**Comment by thomashvmw** [comment]
The vmwgfx patches are now in Linux 5.2-rc2:
63cb44441826
and 
8407f8a1d940
They will probably be in the official stable kernels by next week, and I think fedora 30 will base their official kernel on one of the stable kernel releases, so they will get propagated as a kernel update.

**Comment by thomashvmw** [comment]
Linux kernel fixes are now released in 5.1.8. Fedora updates are currently at 5.1.7.

**Comment by hermidalc** [comment]
Hi @thomashvmw et al - I've checked and verified that this issue is fixed now, Fedora 30 graphical boot works again

**Comment by hermidalc** [comment]
@thomashvmw and VMware team - just want to shout out that Fedora 30 guest is working great on VMware Workstation Pro, i've been using it for a couple weeks now, thank you!

**Comment by billydv** [comment]
Issue still exists on Linux host. Does not appear to be a problem on Windows host. Removing rhgb from /etc/default/grub and recreating grub.cfg does work as expected
