### ISSUE TITLE
VMWare 17.5: Keyboard/Mouse freezes

### ISSUE THREAD

**Issue by DanielEgenolf** [vmware/open-vm-tools#696]
### Describe the bug

Hello,

I am using VMWare Workstation Player since many years with Ubuntu 22.04 without any issues.

After the last upgrade from version 17.0.2 -> 17.5 the keyboard/mouse freezes after a while in my VM. The VM itself does not freeze really because I can still connect to it using ssh. Often the keyboard/mouse freezes after clicking CTRL + Mouse Click.

Unfortunately, it is not possible to get the keyboard/mouse back to the VM. The only way to "fix" this is to restart the VM using the red shutdown button. This issue has been seen by many people (e.g. [vmware bug report](https://communities.vmware.com/t5/VMware-Workstation-Pro/Workstation-17-5-0-enhanced-keyboard-driver-problem/td-p/2991913).

Debug information originating from vmware.log (issue happened during that time):

```
2023-11-14T11:12:29.065Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=0 numPackets=0 status=0 0
2023-11-14T11:12:29.065Z In(05) vmx USBIO:  000: 00 03 01 00 00 00 00 00                         ........        
2023-11-14T11:12:29.065Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=0 numPackets=0 status=0 0
2023-11-14T11:12:29.065Z In(05) vmx USBIO:  000: 00 03 01 00 00 00 00 00                         ........        
2023-11-14T11:12:29.114Z In(05) vmx GuestRpc: Got RPCI vsocket connection 11, assigned to channel 1.
2023-11-14T11:12:29.114Z In(05) vmx Guest: [vgauthservice] VGAuthService END SERVICE
2023-11-14T11:12:29.115Z In(05) vmx GuestRpc: Closing channel 1 connection 11
2023-11-14T11:12:29.126Z Wa(03) vmx Guest attempted to revert hostVerifiedSamlToken capability; ignoring.
2023-11-14T11:12:29.131Z In(06) vmx ConfigDB: No data written - no change detected.
2023-11-14T11:12:29.131Z In(06) vmx ConfigDB: VM config file was not updated with latest dictionary edits.
2023-11-14T11:12:29.137Z In(05) vcpu-2 GuestRpc: Reinitializing Channel 2(toolbox)
2023-11-14T11:12:29.137Z In(05) vcpu-2 Tools: [AppStatus] Last heartbeat value 125 (last received 0s ago)
2023-11-14T11:12:29.137Z In(05) vcpu-2 TOOLS: appName=toolbox, oldStatus=1, status=0, guestInitiated=1.
2023-11-14T11:12:29.157Z In(06) vcpu-2 ConfigDB: No data written - no change detected.
2023-11-14T11:12:29.157Z In(06) vcpu-2 ConfigDB: VM config file was not updated with latest dictionary edits.
2023-11-14T11:12:29.159Z In(06) vcpu-2 GuestRpc: Channel 2 reinitialized.
2023-11-14T11:12:29.161Z In(05) vmx GuestRpc: Got error for channel 0 connection 7: Remote disconnected
2023-11-14T11:12:29.161Z In(05) vmx GuestRpc: GuestRpcResetVsockChannel: channel 0
2023-11-14T11:12:29.161Z In(05) vmx GuestRpc: Closing channel 0 connection 7
2023-11-14T11:12:29.545Z In(05) vmx USBIO: GetStatus
2023-11-14T11:12:29.545Z In(05) vmx USBIO: (device=0)
2023-11-14T11:12:29.545Z In(05) vmx USBIO: 
2023-11-14T11:12:29.545Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=2 numPackets=0 status=0 0
2023-11-14T11:12:29.545Z In(05) vmx USBIO:  000: 80 00 00 00 00 00 02 00                         ........        
2023-11-14T11:12:29.545Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=2 numPackets=0 status=0 0
2023-11-14T11:12:29.545Z In(05) vmx USBIO:  000: 80 00 00 00 00 00 02 00                         ........        
2023-11-14T11:12:29.545Z In(05) vmx USBIO:  000: 03 00                                           ..              
2023-11-14T11:12:29.547Z In(05) vmx USBIO: ClearFeature
2023-11-14T11:12:29.547Z In(05) vmx USBIO: (feature=1, device=0)
2023-11-14T11:12:29.547Z In(05) vmx USBIO: 
2023-11-14T11:12:29.547Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=0 numPackets=0 status=0 0
2023-11-14T11:12:29.547Z In(05) vmx USBIO:  000: 00 01 01 00 00 00 00 00                         ........        
2023-11-14T11:12:29.547Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=0 numPackets=0 status=0 0
2023-11-14T11:12:29.547Z In(05) vmx USBIO:  000: 00 01 01 00 00 00 00 00                         ........        
2023-11-14T11:12:29.548Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0001)
2023-11-14T11:12:29.548Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.548Z In(05) vmx USBIO:  000: a3 00 00 00 01 00 04 00                         ........        
2023-11-14T11:12:29.548Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0001)
2023-11-14T11:12:29.548Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.548Z In(05) vmx USBIO:  000: a3 00 00 00 01 00 04 00                         ........        
2023-11-14T11:12:29.548Z In(05) vmx USBIO:  000: 07 01 00 00                                     ....            
2023-11-14T11:12:29.550Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0002)
2023-11-14T11:12:29.550Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.550Z In(05) vmx USBIO:  000: a3 00 00 00 02 00 04 00                         ........        
2023-11-14T11:12:29.550Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0002)
2023-11-14T11:12:29.550Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.550Z In(05) vmx USBIO:  000: a3 00 00 00 02 00 04 00                         ........        
2023-11-14T11:12:29.550Z In(05) vmx USBIO:  000: 00 01 00 00                                     ....            
2023-11-14T11:12:29.551Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0003)
2023-11-14T11:12:29.551Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.551Z In(05) vmx USBIO:  000: a3 00 00 00 03 00 04 00                         ........        
2023-11-14T11:12:29.551Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0003)
2023-11-14T11:12:29.551Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.551Z In(05) vmx USBIO:  000: a3 00 00 00 03 00 04 00                         ........        
2023-11-14T11:12:29.551Z In(05) vmx USBIO:  000: 00 01 00 00                                     ....            
2023-11-14T11:12:29.552Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0004)
2023-11-14T11:12:29.552Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.552Z In(05) vmx USBIO:  000: a3 00 00 00 04 00 04 00                         ........        
2023-11-14T11:12:29.552Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0004)
2023-11-14T11:12:29.552Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.552Z In(05) vmx USBIO:  000: a3 00 00 00 04 00 04 00                         ........        
2023-11-14T11:12:29.552Z In(05) vmx USBIO:  000: 00 01 00 00                                     ....            
2023-11-14T11:12:29.554Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0005)
2023-11-14T11:12:29.554Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.554Z In(05) vmx USBIO:  000: a3 00 00 00 05 00 04 00                         ........        
2023-11-14T11:12:29.554Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0005)
2023-11-14T11:12:29.554Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.554Z In(05) vmx USBIO:  000: a3 00 00 00 05 00 04 00                         ........        
2023-11-14T11:12:29.554Z In(05) vmx USBIO:  000: 00 01 00 00                                     ....            
2023-11-14T11:12:29.555Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0006)
2023-11-14T11:12:29.555Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.555Z In(05) vmx USBIO:  000: a3 00 00 00 06 00 04 00                         ........        
2023-11-14T11:12:29.555Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0006)
2023-11-14T11:12:29.555Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.555Z In(05) vmx USBIO:  000: a3 00 00 00 06 00 04 00                         ........        
2023-11-14T11:12:29.555Z In(05) vmx USBIO:  000: 00 01 00 00                                     ....            
2023-11-14T11:12:29.556Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0007)
2023-11-14T11:12:29.556Z In(05) vmx USBIO: Down dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.556Z In(05) vmx USBIO:  000: a3 00 00 00 07 00 04 00                         ........        
2023-11-14T11:12:29.556Z Wa(03) vmx USBIO: Class 0x00(wValue=0x0000, wIndex=0x0007)
2023-11-14T11:12:29.556Z In(05) vmx USBIO: Up dev=3 'usb:1' endpt=0 stream=0 datalen=4 numPackets=0 status=0 0
2023-11-14T11:12:29.556Z In(05) vmx USBIO:  000: a3 00 00 00 07 00 04 00                         ........        
2023-11-14T11:12:29.556Z In(05) vmx USBIO:  000: 00 01 00 00                                     ....            
2023-11-14T11:12:29.693Z Wa(03) vcpu-1 VMMouse: CMD Received 0x000000f5 with 16 words of unread data!
2023-11-14T11:12:29.693Z In(05) vcpu-1 VMMouse: CMD Disable
2023-11-14T11:12:29.693Z In(05) vcpu-1 VMMouse: Disabling VMMouse mode
```

Is this problem related to the VMWare software itself or perhaps to the VMWare tools?

Any help appreciated.

Thanks in advance
Daniel

### Reproduction steps

1. Use VMWare Workstation Player 17.5
2. Start VM (e.g. Ubuntu, SLES)
3. After a while the keyboard/mouse freezes, especially when using the key "CTRL" in combination with a mouse click

### Expected behavior

The keyboard/mouse should not freeze.

**Comment by mattheweshleman** [comment]
Likely same issue. Win11 host, VMWare Workstation Pro 17.5, Debian 11 guest. Everything auto-updating to latest, etc.

For some reason, it happens more often when using JetBrains IDE within VM/Debian11.  Key will be stuck, and repeating within IDE (within VM) and I have been unable to find a way to stop it, short of powering down the VM and restarting the VM.

**Comment by DanielEgenolf** [comment]
I can reproduce this issue by pressing a random key + mouse click. Immediately, the keyboard/mouse freezes.
@mattheweshleman: Yes, it freezes by my VM too when using JetBrains IDE or Eclipse IDE.

**Comment by DanielEgenolf** [comment]
Setting the following vmware parameters into the config file helped me:
keyboard.allowBothIRQs = "FALSE"
keyboard.vusb.enable = "TRUE"
see [vmware comment](https://communities.vmware.com/t5/VMware-Workstation-Pro/Workstation-17-5-0-enhanced-keyboard-driver-problem/m-p/2995695/highlight/true#M183774).

**Comment by AlexanderProd** [comment]
I'm experiencing the same problem with on Win 11 with VMWare Workstation Pro 17.5 running Ubuntu 23.10. I also have the VMWare ehanced keyboard driver installed.

**Comment by edermi** [comment]
I'm facing the same issue and had to reboot VMs like 20 times the last two weeks, unfortunately I cannot reproduce the error consistently. In my experience, it often happened when copying stuff with `Ctrl+Shift+C` from a VM terminal window (i3 + xfce4-terminal), which locks up IO and continues to send 'c' characters to the terminal. The VM continues running, but without being able to interact with it, reboot has always been my last resort.

Host: Windows 10
Guest: Kali
VMware Workstation 17 Pro (17.5.0 build-22583795)
I've got the keyboard driver installed, I'm going to try @DanielEgenolf's recommendation to see if it works around this issue.

**Comment by UnicycleBloke** [comment]
I'm using 17.5.0 build-22583795 and I have seen this bug many times in a couple of days. I am forced to power down and reboot the VM every time.

**Comment by edermi** [comment]
@DanielEgenolf's recommendation seems to work around the problem, not having a single hang for several days of intense work in VMs now.

**Comment by jayraj0x01** [comment]
@edermi i am facing the same issue whenever i Copy | Paste something , it freezes and don't get normal without reboot , sometimes on the lock screen,  this issue needs to be fix asap i am having so many troubles imagine you are doing an important work and your vm just freezes your all work is gone . Fix This !!!!!

**Comment by AbdelrahmanMohamedDesoky** [comment]
I'm also having the same issue but I didn't encounter this issue on V16 or previous versions

this solution fixed it for me : https://communities.vmware.com/t5/VMware-Workstation-Pro/Workstation-17-5-0-enhanced-keyboard-driver-problem/m-p/2995695/highlight/true#M183774

**Comment by juergenil** [comment]
Mouse and keyboard sometimes were freezing.
For me, adding "keyboard.allowBothIRQs = FALSE" to vmx file solved the issue.
Host OS: Windows 11 22H2, Guest OS Win11 23H2.

**Comment by reybango** [comment]
> Setting the following vmware parameters into the config file helped me: keyboard.allowBothIRQs = "FALSE" keyboard.vusb.enable = "TRUE" see [vmware comment](https://communities.vmware.com/t5/VMware-Workstation-Pro/Workstation-17-5-0-enhanced-keyboard-driver-problem/m-p/2995695/highlight/true#M183774).

This seems to have also helped with the freezing issue when using VMWare WS Pro 17.5

**Comment by lawweiliang** [comment]
> Same problem on Kali Linux VM. Doesn't happen on Windows box, so it's issue with tools I guess. The bypass that was commented here helps, but the VMX file is getting edited after you run Workstation again, so you need to remember to edit file once again.
@LongWayHomie 

No need to re-edit the file.

Yes, when you restart the VM. VM will reposition the configuration file. 

Before
![image](https://github.com/vmware/open-vm-tools/assets/34936929/b137aae1-1618-46ab-bffa-85ab469da1ce)

After
![image](https://github.com/vmware/open-vm-tools/assets/34936929/74096263-2be1-49e0-afa5-ba1320a57220)

**Comment by DanielEgenolf** [comment]
It looks like that this issue is not related to the open-vm-tools. It's a bug in the latest VMWare Player software. That's why I am closing this issue.

**Comment by darkomenx** [comment]
For anybody go through it and he wondering what kind of file all speak.
You need to edit this file : <dir_of_your_VM>/<name_vm>.vmx

dir_of_your_VM : not the installation of VMWare ! It's installation of YOUR VM data

And I also confirm in my part that the fix resolve my freeze VM issue. 

I hope that helping you.

**Comment by dtromb** [comment]
Still having this issue after applying the "fix" described here.    We're in a state now at this current moment when all of the major VM platforms (VirtualBox, VMWare, qemu) for guest Linux have showstopping, forced reboot bugs going on.   Please, please give this extremely high priority.

**Comment by adamitj** [comment]
For those looking for a fix VMWare claims it is resolved on v17.5.1 as stated here:

[VMware Workstation 17.5.1 Pro Release Notes](https://docs.vmware.com/en/VMware-Workstation-Pro/17.5.1/rn/vmware-workstation-1751-pro-release-notes/index.html)

I did not test it, but will.

**Comment by pontazaricardo** [comment]
For the people adding the flags
keyboard.allowBothIRQs = "FALSE"
keyboard.vusb.enable = "TRUE"
to their config files: If you have a serial-port device connected (ttyUSB0), it hangs and the connection gets lost. 

Applying the 17.5.1 update and removing the flags fixed the problem.

**Comment by wwwrob** [comment]
> For the people adding the flags keyboard.allowBothIRQs = "FALSE" keyboard.vusb.enable = "TRUE" to their config files: If you have a serial-port device connected (ttyUSB0), it hangs and the connection gets lost.
> 
> Applying the 17.5.1 update and removing the flags fixed the problem.

I didn't modify the configs, using 17.5.1 build-23298084 issue is still present.

**Comment by wwwrob** [comment]
This build is very unstable, experiencing freezes, host needs to be restarted. How did this even pass QA..? As someone who has to maintain work VMs, this is really bad. I'll be looking into alternatives.

**Comment by ischilling** [comment]
I see this problem in 17.5.2 build-23775571 - I can reproduce it during the installation of Windows Server 2022 and in already existing versions of Windows Server 2022 as well as with most recent Windows 11 versions, both, during installation as well as with already installed and so far working VMs. The ladder worked perfect before update to V 17.5.x.

keyboard.allowBothIRQs = "FALSE"
keyboard.vusb.enable = "TRUE"

Doesn't work at all :(

**Comment by sokzmalin** [comment]
Hey, I'm using VMWare 17.5.2 build-23775571 and this issue still occurs. Guest OS (ubuntu) in VM freezes after random time (usually after a dozen minutes). In host OS (Windows 10) I see a high CPU usage - percentage is proportional to number of cores used. This is getting annoying that such issue is still not solved. Is there any bug opened for this?

**Comment by darkomenx** [comment]
You need to switch on VMWare Workstation 17 Pro

**Comment by LMMental76** [comment]
I had this problem in Ubuntu 24.04.1 under VMware Workstation 17.6.2.  I tried a lot of the suggestions here, but none of them worked - [this ultimately ended up being the answer for me](https://www.reddit.com/r/vmware/comments/16x3t7j/comment/k3p1xb1/).

I disabled all of my IDE optical drives and I'm no longer getting keyboard stuttering and the VM is generally behaving much more responsively.

**Comment by sebres** [comment]
> I'm using VMWare 17.5.2 build-23775571 and this issue still occurs. Guest OS (ubuntu) in VM freezes after random time (usually after a dozen minutes). In host OS (Windows 10) I see a high CPU usage - percentage is proportional to number of cores used.

I had the same issue sporadically with a linux guest (in windows guest), that going slower and slower with the time (up to complete freeze and 100% load of all vCPUs reserved for the guest) using 17.6.2 build-24409262.
Trying dozen "solution" suggestions, inclusive attempts to fix kernel bug "IDE drives and indefinite polling by the SCSI driver", related to this [thread](https://lore.kernel.org/linux-scsi/20230915022034.678121-1-dlemoal@kernel.org/) (let alone I did not have IDE-drives at all in VM), etc - and nothing helped.
But since in the time of not-full freeze besides other processes I found the vmware tools daemon with high load too, I decided to uninstall it in the guest.
So replaced the tools provided by vmware workstation with open source implementation [open-vm-tools](https://packages.debian.org/stable/open-vm-tools), e. g. did this:
```
/usr/bin/vmware-uninstall-tools.pl
apt install open-vm-tools
```
and after the switch it seems not to freeze anymore on my side.

Hope this would help.

**Comment by johnwvmw** [comment]
@sebres  and everyone.

The VMware Tools for Linux provided on Workstation or Fusion is only to be used on legacy Linux guests - circe Centos 6 and earlier.  

All other Linux guests are expected to use the open-vm-tools packages provided by the Linux vendor for the specifc Linux release {version).

**Comment by Delitants** [comment]
> > Same problem on Kali Linux VM. Doesn't happen on Windows box, so it's issue with tools I guess. The bypass that was commented here helps, but the VMX file is getting edited after you run Workstation again, so you need to remember to edit file once again.
> > [@LongWayHomie](https://github.com/LongWayHomie)
> 
> No need to re-edit the file.
> 
> Yes, when you restart the VM. VM will reposition the configuration file.
> 
> Before ![image](https://github.com/vmware/open-vm-tools/assets/34936929/b137aae1-1618-46ab-bffa-85ab469da1ce)
> 
> After ![image](https://github.com/vmware/open-vm-tools/assets/34936929/74096263-2be1-49e0-afa5-ba1320a57220)

Does not help. I need to connect a USB device in 2.0 mode and after start keyborad and mouse get unresponsive. Latest VMWAre Fusion for Mac. Works only in USB 3.0 mode.
