### ISSUE TITLE
Guest customization not working on CentOS

### ISSUE THREAD

**Issue by aptituz** [vmware/open-vm-tools#76]
The guest customization is failing to detect release version on Centos7 and therefore refusing to change guest settings. Changing the content of /etc/redhat_release to "Red Hat Enterprise Linux Server release 7.0 (Maipo)" is a work around for the problem, but since other tools are evaluating that file as well, it cannot be said what could break.

Further informations about the problem can be found on: https://lonesysadmin.net/2015/01/06/centos-7-refusing-vmware-vsphere-guest-os-customizations/

Using the vmware supplied deployPkg package isn't an option, unfortunately, because the open-vm-tools in CentOS are too new (9.10.2-4.el7.x86_64.rpm)

**Comment by aneverov4vmw** [comment]
Hi,

Regrettably, this one is a known issue and it's not related to open-vm-tools or deployPkg, but rather to the Guest Customization Engine used by vCenter. The way we determine how to customize is based on the OS identification strings. In http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf you can see that on the 5.5.x line CentOS7 support has been added one update release later than RHEL7. The only actual issue was that the id string didn't make it on time, that's why the workaround works.

**Comment by ravindravmw** [comment]
The same question was asked before in issue #65.

**Comment by aptituz** [comment]
So just to get it right: With vCenter 5.5 it should work given it has the latest updates?

**Comment by aneverov4vmw** [comment]
Yes, the issue has been fixed in vCenter 5.5 Update 3. 

Also the pdf mentioned above is the official document. It's updated regularly to include the latest changes.

**Comment by moander** [comment]
deployPkg requires perl to be installed on the guest by the way

```
yum install -y perl
```

**Comment by borisovano** [comment]
I've tried the workaround with Centos 7.2.1511, vCenter 5.5.0 Build 1879799.
(Have no control over our vCenter upgrades hence)

It doesn't work for me. Still seeing 'WARNING: Unknown RedHat Linux Distribution distribution flavour' in the log file and wrong files are customized(same as in #65).

toolsDeployPkg.log attached.
[toolsDeployPkg.log.txt](https://github.com/vmware/open-vm-tools/files/243177/toolsDeployPkg.log.txt)

 Any ideas how can I debug this further?

**Comment by aneverov4vmw** [comment]
Hi,

In that version of vCenter we do not search for the OS identification string in /etc/redhat-release. We search in /etc/issue instead. The log shows that we can't find anything in there:

DEBUG: Reading issue file ...  
DEBUG: Command: cat /etc/issue 
DEBUG: Result: \S
Kernel \r on an \m

Please put the OS identification string into /etc/issue and it should work fine.

**Comment by borisovano** [comment]
@aneverov4vmw , thanks for your reply. I've deleted my comment after reading your os-customization-matrix link with the thought that Centos\RHEL 7 are not supported at all in my vCenter version.

I've tried your suggestion, the OS was indeed identified however customization still didn't work.
Attaching the new log.
[toolsDeployPkg_try2.log.txt](https://github.com/vmware/open-vm-tools/files/243267/toolsDeployPkg_try2.log.txt)


Original comment(deleted by mistake):
==========================================================================
I've tried the above workaround with Centos 7.2.1511, vCenter 5.5.0 Build 1879799.
(Have no control over our vCenter upgrades)

It doesn't work for me. Still seeing 'WARNING: Unknown RedHat Linux Distribution distribution flavour' in the log file and wrong files are customized(same as in #65).

toolsDeployPkg.log attached.
toolsDeployPkg.log.txt

Any ideas how can I debug this further?

**Comment by aneverov4vmw** [comment]
Sorry, I missed that your vCenter build corresponds to some Update1 patch. So, yes - as the matrix says, RHEL7/CentOs7 is not supported on that build. The code is simply missing there, so there is no way to make it work.

**Comment by borisovano** [comment]
Thank you for your help and the fast response!

**Comment by Everything-Virtual** [comment]
So I am having the same issues, CentOS 7.1 and 7.2, installed on a vSphere 6 environment (VCSA).

I have tried the following steps.

Installed a minimal installation, manually installed perl, open-vm-tools, yum update (and later I also changed the redhat-release to reflect RHEL 7.0 (Maipo)) - Templates would deploy with hostname.local.

Installed an infrastructure build, added the guest agents and once the installation completed I did a yum update (and later I also changed the redhat-release to reflect RHEL 7.0 (Maipo)) - Templates would deploy with hostname.local.

I have confirmed that perl was installed on both OS VMs, I can confirm that open-vm-tools was installed (9.10), I can confirm that net-tools was present.

With both flavours of the OS I also did a release where I did a sys-unconfig prior to template creation rather than just powering down. 

Additionally I also created templates where I did the following:

> service rsyslog stop
> service auditd stop
> 
> package-cleanup --oldkernels --count=1
> 
> /usr/bin/yum clean all
> 
> /usr/sbin/logrotate -f /etc/logrotate.conf
> /bin/rm -f /var/log/*-???????? /var/log/*.gz
> /bin/rm -f /var/log/dmesg.old
> /bin/rm -rf /var/log/anaconda
> /bin/cat /dev/null > /var/log/audit/audit.log
> /bin/cat /dev/null > /var/log/wtmp
> /bin/cat /dev/null > /var/log/lastlog
> /bin/cat /dev/null > /var/log/grubby
> 
> /bin/rm -f /etc/udev/rules.d/70*
> 
> /bin/sed -i(.bak)  '/UUID/d' /etc/sysconfig/network-scripts/ifcfg-eno16777984
> 
> /bin/rm -f /etc/ssh/*key*
> 
> /bin/rm -f ~root/.bash_history
> unset HISTFILE
> 
> /bin/rm -rf ~root/.ssh/

Having converted both VMs to templates I deploy from them and then checked for any mention of customization-guest in /var/log/messages but nothing is present.

I also tried looking for the name of the VM in /var/log/messages but there wasn't any mention of that either.

Environment is as follows.

vSphere 6 (ESXi 6 Update 2, VCSA Build 3634794)
CentOS 7.1 1503
CentOS 7/2 1511

All in all both versions of the OS were templated at least 4 times with various states and none of them worked.

At this stage I am stumped so any help would be great.

**Comment by whatever1985** [comment]
I would just add that currently Guest Customization (GOSC as we call it) related logging goes into files under /var/log/vmware-imc/ (typically toolsDeployPkg.log) instead of syslog. toolsDeployPkg.log usually provides good clues on what operations GOSC was trying to perform. If it's not present (or, in case of re-used template/VM, has old access time), it would mean GOSC hasn't had a chance to run.

**Comment by aneverov4vmw** [comment]
I would just add that currently Guest Customization (GOSC as we call it) related logging goes into files under /var/log/vmware-imc/ (typically toolsDeployPkg.log) instead of syslog. toolsDeployPkg.log usually provides good clues on what operations GOSC was trying to perform. If it's not present (or, in case of re-used template/VM, has old access time), it would mean GOSC hasn't had a chance to run.

**Comment by voiprodrigo** [comment]
Hello,

Sorry to revive this, but I'm having problems with guest customization. I'm using vCenter 6 and ESXi 6.0u2. I've built CentOS 7.2 VM template that has open-vm-tools 9.10.2 and perl installed. The guest os type is rhel7-64, and I've modified /etc/release to have the RHEL release info, as noted on multiple blog posts. Yet, I can't seem to this running, always fails with UncustomizableGuest error. No vmware-inc dir in /var/log too. 

Any hints? 

Thanks.

**Comment by scaronni** [comment]
I've fixed `open-vm-tools` in EPEL 6 and Fedora to include Perl as a dependency for the `DeployPkg` plugin. Proprietary VMWare tools packages set the dependency on the `vmware-tools-foundation` packages.

https://bodhi.fedoraproject.org/updates/?packages=open-vm-tools

I've opened a case on Red Hat for the RHEL 7 package, as I have no access there.

**Comment by jtyr** [comment]
I'm having the same issue. My cloud provider is saying that they are running vCenter v5.5 update 3d but the problem is still there. Is there any way (an API call) how can I check the vCenter version?

**Comment by stanguturi** [comment]
From inside the VM, it's not possible to figure out the version of vCenter that is managing the VM. If you have the IP address of the 'vCenter', you can login using 'vSphere client' and get the version from 'Help -> About vCenter' section.

**Comment by jtyr** [comment]
Thanks for the details, @stanguturi but I have access only to the vCloud Director web UI and its API.

**Comment by stanguturi** [comment]
@jtyr I think you need to have org admin / vCD Admin Access. **Try out** the following steps if they work.

- Find out the Org VDC where the VM is deployed
- Then find the Provider VDC for this Org VDC
- In the Provider VDC configuration pane, one might be able to find which VC is used to create it

Thanks

**Comment by stanguturi** [comment]
> Yes, the issue has been fixed in vCenter 5.5 Update 3.
>
> Also the pdf mentioned above is the official document. It's updated regularly to include the latest changes.

As @aneverov4vmw mentioned earlier, the issue should be fixed in the latest VC releases (atleast from 5.5). Closing the issue.
